/**
 * HÜE Prisma › Formatos — copy de la pantalla (español e inglés, como el resto de Prisma). Módulo puro.
 */
import { t, type Par } from "../copy.ts";
import type { Modo, Plataforma } from "./geometria.ts";

export const PLATAFORMA_LABEL: Record<Plataforma, Par> = {
  meta: t("Meta (Facebook e Instagram)", "Meta (Facebook & Instagram)"),
  google: t("Google Display", "Google Display"),
  linkedin: t("LinkedIn", "LinkedIn"),
  x: t("X", "X"),
  pinterest: t("Pinterest", "Pinterest"),
  youtube: t("YouTube (miniatura)", "YouTube (thumbnail)"),
  otro: t("Medida libre", "Custom size"),
};

export const MODO_LABEL: Record<Modo, Par> = {
  extender: t("Extender", "Extend"),
  ia: t("IA", "AI"),
  blur: t("Desenfoque", "Blur"),
  color: t("Color", "Color"),
};

export const MODO_AYUDA: Record<Modo, Par> = {
  extender: t("Continúa los bordes lisos o degradados del anuncio. Gratis.", "Continues the ad's plain or gradient edges. Free."),
  ia: t("H.Ü.E continúa el fondo del anuncio hacia afuera.", "H.Ü.E extends the ad's background outward."),
  blur: t("El mismo anuncio, desenfocado y oscurecido, detrás. Gratis.", "The same ad, blurred and darkened, behind it. Free."),
  color: t("Un color sólido alrededor. Gratis.", "A solid color around it. Free."),
};

export const FX = {
  titulo: t("Formatos", "Formats"),
  tagline: t("Un anuncio terminado, en todos los tamaños. El contenido nunca se toca: sólo se escala (y se recorta fondo liso si hace falta).", "One finished ad, in every size. The content is never touched: only scaled (and plain background trimmed when needed)."),
  volver: t("Volver a HÜE Prisma", "Back to HÜE Prisma"),
  puertaTitulo: t("Formatos", "Formats"),
  puertaAyuda: t("Lleva un anuncio terminado a todos los tamaños de Meta, Google y más.", "Take a finished ad to every Meta, Google and other size."),
  subir: t("Sube el anuncio terminado", "Upload the finished ad"),
  subirAyuda: t("Arrástralo aquí o elige el archivo. Una imagen plana (sin capas).", "Drag it here or pick the file. A flat image (no layers)."),
  subirTipos: t("PNG · JPG · WebP · hasta 25 MB", "PNG · JPG · WebP · up to 25 MB"),
  subiendo: t("Subiendo…", "Uploading…"),
  revisando: t("Revisando el archivo…", "Checking the file…"),
  cargandoResultado: t("Trayendo la imagen del resultado…", "Bringing in the result image…"),
  marca: t("Marca (para sus colores)", "Brand (for its colors)"),
  sinMarca: t("Sin marca", "No brand"),
  original: t("Original", "Original"),
  cambiar: t("Cambiar anuncio", "Change ad"),
  tamanos: t("Tamaños", "Sizes"),
  todos: t("Todos", "All"),
  ninguno: t("Ninguno", "None"),
  rediseno: t("Requiere rediseño", "Needs a redesign"),
  medidaLibre: t("Agregar medida libre", "Add a custom size"),
  ancho: t("Ancho", "Width"),
  alto: t("Alto", "Height"),
  medidaInvalida: t("Entre {min} y {max} px por lado.", "Between {min} and {max} px per side."),
  colorRelleno: t("Color del relleno", "Fill color"),
  costoReal: t("Costo real: {c}", "Actual cost: {c}"),
  generar: t("Generar {n} tamaños", "Generate {n} sizes"),
  generarUno: t("Generar 1 tamaño", "Generate 1 size"),
  elegirAlMenosUno: t("Elige al menos un tamaño.", "Pick at least one size."),
  resultados: t("Resultados", "Results"),
  pendiente: t("En fila", "Queued"),
  procesando: t("Armando…", "Building…"),
  error: t("No salió", "Failed"),
  reintentar: t("Reintentar", "Retry"),
  bajarPng: t("PNG", "PNG"),
  bajarJpg: t("JPG", "JPG"),
  bajarZip: t("Descargar ZIP", "Download ZIP"),
  armandoZip: t("Armando ZIP…", "Building ZIP…"),
  zipAyuda: t("PNG (original exacto) y JPG (más ligero) de cada tamaño.", "PNG (exact original) and JPG (lighter) of each size."),
  sinConexion: t("Sin conexión con el servidor. Reintenta.", "No connection to the server. Retry."),
  demo: t("Vista de muestra: nada se guarda.", "Sample view: nothing is saved."),
  // ── reap 2026-10-02: todo lo que antes vivía sólo en un `title` ahora se ve ──
  redisenoPorque: t("ocuparía sólo el {p} % del lienzo", "would cover only {p}% of the canvas"),
  seAmplia: t("Se amplía ×{x}: se verá algo borroso", "Enlarged ×{x}: it will look a bit blurry"),
  modoRelleno: t("Relleno", "Fill"),
  leyenda: t("Cómo se rellena lo que sobra alrededor del anuncio:", "How the space around the ad is filled:"),
  iaApagadaBanner: t("El relleno con IA todavía no está activo. Usa Desenfoque o Color; cuando se active, aparecerá aquí.", "AI fill isn't active yet. Use Blur or Color; it will show up here once it's on."),
  precioIa: t("≈ {c} c/u", "≈ {c} each"),
  elegidos: t("{n} elegidos", "{n} selected"),
  maxTamanos: t("Máximo {n} tamaños por anuncio.", "Up to {n} sizes per ad."),
  todosAria: t("Elegir todos los tamaños (menos los que requieren rediseño)", "Select all sizes (except those needing a redesign)"),
  ningunoAria: t("Quitar todos los tamaños", "Clear all sizes"),
  medidaYaEsta: t("Ese tamaño ya está en la lista.", "That size is already on the list."),
  medidaAgregada: t("Agregado {w}×{h}.", "Added {w}×{h}."),
  quitarMedida: t("Quitar {w}×{h}", "Remove {w}×{h}"),
  gratis: t("Gratis", "Free"),
  costoAntes: t("Costo estimado", "Estimated cost"),
  porGenerar: t("{n} por generar · {ia} con IA", "{n} to generate · {ia} with AI"),
  todoListo: t("Todo lo elegido ya está listo.", "Everything selected is ready."),
  resumen: t("{ok} listos · {mal} no salieron", "{ok} ready · {mal} failed"),
  resumenOk: t("{ok} tamaños listos", "{ok} sizes ready"),
  reintentarFallidos: t("Reintentar los que no salieron", "Retry the failed ones"),
  progreso: t("{listos} de {n} listos", "{listos} of {n} ready"),
  enOtraPestana: t("Se está armando (quizá en otra pestaña).", "Being built (maybe in another tab)."),
  cambiarConfirmar: t("Se pierden {n} tamaños de la vista (descárgalos antes). ¿Cambiar el anuncio?", "{n} sizes will leave this view (download them first). Change the ad?"),
  siCambiar: t("Sí, cambiar", "Yes, change"),
  cancelar: t("Cancelar", "Cancel"),
  bajarZipN: t("Descargar ZIP ({n})", "Download ZIP ({n})"),
  zipListo: t("ZIP descargado.", "ZIP downloaded."),
  enlaceVencido: t("No se pudo descargar. Reintenta en un momento.", "Download failed. Retry in a moment."),
  rehacerCon: t("Rehacer · {m}", "Redo · {m}"),
  verGrande: t("Ver grande", "View large"),
  intactoCorto: t("Original sin cambios", "Original unchanged"),
  revisarUnionCorto: t("Revisa el borde donde el fondo nuevo toca tu anuncio; si se nota, prueba Desenfoque.", "Check the edge where the new background meets your ad; if it shows, try Blur."),
  subirError: t("No se pudo subir. Reintenta.", "Upload failed. Retry."),
  subirTipoMal: t("Sólo PNG, JPG o WebP.", "Only PNG, JPG or WebP."),
  subirPeso: t("El anuncio pesa más de 25 MB.", "The ad is over 25 MB."),
  frenado: t("No se mandó: demasiados tamaños en poco tiempo. Reintenta en unos minutos.", "Not sent: too many sizes in a short time. Retry in a few minutes."),
  resumenUno: t("1 tamaño listo", "1 size ready"),
  resumenEnCurso: t("{n} todavía armándose", "{n} still building"),
  resultadoError: t("No pudimos traer la imagen del resultado ({e}). Súbela a mano.", "We couldn't bring in the result image ({e}). Upload it by hand."),
  colorBordeLabel: t("Color del borde del anuncio", "The ad's edge color"),
  colorMarca: t("Color de la marca {c}", "Brand color {c}"),
  // ── v2 (2026-10-09): pegar la lista del cliente + recorte de fondo liso ──
  pegarLista: t("Pegar la lista del cliente", "Paste the client's list"),
  pegarAyuda: t("Tal cual te la mandaron, p. ej. «9:16 (1080×1920) 320×250 1200*627». Se eligen exactamente esas medidas.", "As they sent it, e.g. “9:16 (1080×1920) 320×250 1200*627”. Exactly those sizes get selected."),
  pegarUsar: t("Usar estas medidas", "Use these sizes"),
  pegarNada: t("No encontré medidas. Escríbelas como 320×250.", "No sizes found. Write them like 320×250."),
  pegarListo: t("{n} medidas de la lista · {on} elegidas", "{n} sizes from the list · {on} selected"),
  pegarRediseno: t(" · {r} requieren rediseño (quedan apagadas)", " · {r} need a redesign (left off)"),
  pegarFuera: t(" · fuera de límites, ignoradas: {m}", " · out of bounds, ignored: {m}"),
  pegarTope: t(" · sólo caben {n} por anuncio", " · only {n} fit per ad"),
  recorta: t("Recorta {p} % de fondo liso", "Trims {p}% of plain background"),
};
