-- ═══════════════════════════════════════════════════════════════
-- 0072 — HÜE Prisma · los modelos de cada herramienta, EN HIGGSFIELD (sólo datos)
-- ═══════════════════════════════════════════════════════════════
-- Desde el 2026-09-16 el equipo genera todo en Higgsfield (default para todas las marcas). El
-- catálogo del código (catalogo.ts, CATALOGO_BASE) cambió los modelos de las 5 herramientas que ya
-- tenían fila en 0071: "cómo llegar" ahora explica el camino EN Higgsfield, cada modelo trae su
-- página (`url`, slugs verificados en higgsfield.ai) y se suman Image Auto (Nano Banana) y Kling 3.0
-- Motion Control (Kling), que sólo aparecen en "¿en cuál lo generaste?". Las familias nuevas
-- (seedream, seedance, gemini_omni) no necesitan fila: sin fila, la app usa las constantes.
-- Sólo `modelos` (límites y fortalezas no cambian) y SÓLO en las filas que nadie editó en el Hub
-- (`updated_by is null`): lo editado a mano no se pisa; ahí basta "Valores del código" → Guardar.
-- Generado con fichaAFila(CATALOGO_BASE); test-db comprueba que tras aplicarla leer la tabla da
-- exactamente las constantes. Sin cambios de esquema.
update produccion.prisma_herramientas set modelos = '[{"id":"gemini-3.1-flash-image","etiqueta":"Nano Banana 2","rol":"rapido","como_llegar_es":"En Higgsfield: Image → Nano Banana 2 → sube las referencias en orden y pega el prompt.","como_llegar_en":"In Higgsfield: Image → Nano Banana 2 → upload the references in order and paste the prompt.","url":"https://higgsfield.ai/ai/image?model=nano-banana-2"},{"id":"gemini-3-pro-image","etiqueta":"Nano Banana Pro","rol":"fino","como_llegar_es":"En Higgsfield: Image → Nano Banana Pro → sube las referencias en orden y pega el prompt.","como_llegar_en":"In Higgsfield: Image → Nano Banana Pro → upload the references in order and paste the prompt.","url":"https://higgsfield.ai/ai/image?model=nano-banana-pro"},{"id":"image-auto","etiqueta":"Image Auto","rol":"rapido","como_llegar_es":"En Higgsfield: Image → Auto → pega el prompt (Higgsfield elige el modelo).","como_llegar_en":"In Higgsfield: Image → Auto → paste the prompt (Higgsfield picks the model).","url":null}]'::jsonb, updated_at = now()
  where tool = 'nanobanana' and updated_by is null;
update produccion.prisma_herramientas set modelos = '[{"id":"gpt-image-2.5-flare","etiqueta":"GPT Image 2.5 Flare","rol":"rapido","como_llegar_es":"En Higgsfield: Image → GPT Image 2.5 Flare → adjunta las imágenes en orden y pega el prompt.","como_llegar_en":"In Higgsfield: Image → GPT Image 2.5 Flare → attach the images in order and paste the prompt.","url":"https://higgsfield.ai/ai/image?model=gpt-image-2-5-flare"},{"id":"gpt-image-2.5-sunburst","etiqueta":"GPT Image 2.5 Sunburst","rol":"fino","como_llegar_es":"En Higgsfield: Image → GPT Image 2.5 Sunburst → adjunta las imágenes en orden y pega el prompt.","como_llegar_en":"In Higgsfield: Image → GPT Image 2.5 Sunburst → attach the images in order and paste the prompt.","url":"https://higgsfield.ai/ai/image?model=gpt-image-2-5-sunburst"}]'::jsonb, updated_at = now()
  where tool = 'chatgpt' and updated_by is null;
update produccion.prisma_herramientas set modelos = '[{"id":"veo-3.1-fast-generate-preview","etiqueta":"Veo 3.1 Fast","rol":"rapido","como_llegar_es":"En Higgsfield: Video → Google Veo → Veo 3.1 Fast → pega el JSON completo.","como_llegar_en":"In Higgsfield: Video → Google Veo → Veo 3.1 Fast → paste the full JSON.","url":"https://higgsfield.ai/ai/video?model=veo-3-1-preview"},{"id":"veo-3.1-generate-preview","etiqueta":"Veo 3.1","rol":"fino","como_llegar_es":"En Higgsfield: Video → Google Veo → Veo 3.1 → pega el JSON completo.","como_llegar_en":"In Higgsfield: Video → Google Veo → Veo 3.1 → paste the full JSON.","url":"https://higgsfield.ai/ai/video?model=veo-3-1-preview"}]'::jsonb, updated_at = now()
  where tool = 'veo' and updated_by is null;
update produccion.prisma_herramientas set modelos = '[{"id":"kling-3.0-turbo","etiqueta":"Kling 3.0 Turbo","rol":"rapido","como_llegar_es":"En Higgsfield: Video → Kling 3.0 en su modo rápido (Turbo) → pega el prompt.","como_llegar_en":"In Higgsfield: Video → Kling 3.0 in its fast (Turbo) mode → paste the prompt.","url":"https://higgsfield.ai/ai/video?model=kling3_0"},{"id":"kling-3.0","etiqueta":"Kling 3.0","rol":"fino","como_llegar_es":"En Higgsfield: Video → Kling 3.0 → pega el prompt (la foto va en Start frame).","como_llegar_en":"In Higgsfield: Video → Kling 3.0 → paste the prompt (the photo goes in Start frame).","url":"https://higgsfield.ai/ai/video?model=kling3_0"},{"id":"kling-3.0-motion-control","etiqueta":"Kling 3.0 Motion Control","rol":"fino","como_llegar_es":"En Higgsfield: Video → Motion Control → sube la foto del personaje y el video del movimiento; el prompt describe sólo el escenario y la luz.","como_llegar_en":"In Higgsfield: Video → Motion Control → upload the character photo and the motion video; the prompt only describes the setting and light.","url":"https://higgsfield.ai/ai/video/motion?model=kling-3-motion-control"}]'::jsonb, updated_at = now()
  where tool = 'kling' and updated_by is null;
update produccion.prisma_herramientas set modelos = '[{"id":"higgsfield","etiqueta":"Higgsfield DoP","rol":"fino","como_llegar_es":"En Higgsfield: Video → sube la foto → elige ese preset de cámara → pega el texto.","como_llegar_en":"In Higgsfield: Video → upload the photo → pick that camera preset → paste the text.","url":"https://higgsfield.ai/ai/video"}]'::jsonb, updated_at = now()
  where tool = 'higgsfield' and updated_by is null;
